version: '3'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Japan
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql/data:/var/lib/mysql
  nextjs:
    build: ./nextjs
    command: bash -c "yarn && yarn dev"
    links:
      - mysql:mysql
    ports:
      - "3000:3000"
    environment:
      TZ: Japan
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nextjs:/usr/src/app
